# Address proxy will bind to.
proxy:
  host: 0.0.0.0
  port: 19121

# Destination server which the client will connect to.
# You are only able to join offline mode servers.
destination:
  host: 127.0.0.1
  port: 19132

# Change this when the item palette changes.
shield-item-runtime-id: 355
