name: Maven build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: liberica
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: ProxyServer
          path: target/latency-proxy-1.0.0-SNAPSHOT.jar
